/*
	Copyright (c) 2012, Anatoliy Belsky <ab@php.net>
	All rights reserved.

	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions
	are met:

	- Redistributions of source code must retain the above copyright
	notice, this list of conditions and the following disclaimer.

	- Redistributions in binary form must reproduce the above copyright
	notice, this list of conditions and the following disclaimer in the
	documentation and/or other materials provided with the distribution.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
	"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
	LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
	A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
	HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
	SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
	LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
	DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
	THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
	(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
	OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* $Id$ */

#ifndef TA_PHP_FE_H
#define TA_PHP_FE_H
const zend_function_entry ta_functions[] = {
	PHP_FE(trader_accbands, arg_info_trader_accbands)
	PHP_FE(trader_acos, arg_info_trader_acos)
	PHP_FE(trader_ad, arg_info_trader_ad)
	PHP_FE(trader_add, arg_info_trader_add)
	PHP_FE(trader_adosc, arg_info_trader_adosc)
	PHP_FE(trader_adx, arg_info_trader_adx)
	PHP_FE(trader_adxr, arg_info_trader_adxr)
	PHP_FE(trader_apo, arg_info_trader_apo)
	PHP_FE(trader_aroon, arg_info_trader_aroon)
	PHP_FE(trader_aroonosc, arg_info_trader_aroonosc)
	PHP_FE(trader_asin, arg_info_trader_asin)
	PHP_FE(trader_atan, arg_info_trader_atan)
	PHP_FE(trader_atr, arg_info_trader_atr)
	PHP_FE(trader_avgprice, arg_info_trader_avgprice)
	PHP_FE(trader_avgdev, arg_info_trader_avgdev)
	PHP_FE(trader_bbands, arg_info_trader_bbands)
	PHP_FE(trader_beta, arg_info_trader_beta)
	PHP_FE(trader_bop, arg_info_trader_bop)
	PHP_FE(trader_cci, arg_info_trader_cci)
	PHP_FE(trader_cdl2crows, arg_info_trader_cdl2crows)
	PHP_FE(trader_cdl3blackcrows, arg_info_trader_cdl3blackcrows)
	PHP_FE(trader_cdl3inside, arg_info_trader_cdl3inside)
	PHP_FE(trader_cdl3linestrike, arg_info_trader_cdl3linestrike)
	PHP_FE(trader_cdl3outside, arg_info_trader_cdl3outside)
	PHP_FE(trader_cdl3starsinsouth, arg_info_trader_cdl3starsinsouth)
	PHP_FE(trader_cdl3whitesoldiers, arg_info_trader_cdl3whitesoldiers)
	PHP_FE(trader_cdlabandonedbaby, arg_info_trader_cdlabandonedbaby)
	PHP_FE(trader_cdladvanceblock, arg_info_trader_cdladvanceblock)
	PHP_FE(trader_cdlbelthold, arg_info_trader_cdlbelthold)
	PHP_FE(trader_cdlbreakaway, arg_info_trader_cdlbreakaway)
	PHP_FE(trader_cdlclosingmarubozu, arg_info_trader_cdlclosingmarubozu)
	PHP_FE(trader_cdlconcealbabyswall, arg_info_trader_cdlconcealbabyswall)
	PHP_FE(trader_cdlcounterattack, arg_info_trader_cdlcounterattack)
	PHP_FE(trader_cdldarkcloudcover, arg_info_trader_cdldarkcloudcover)
	PHP_FE(trader_cdldoji, arg_info_trader_cdldoji)
	PHP_FE(trader_cdldojistar, arg_info_trader_cdldojistar)
	PHP_FE(trader_cdldragonflydoji, arg_info_trader_cdldragonflydoji)
	PHP_FE(trader_cdlengulfing, arg_info_trader_cdlengulfing)
	PHP_FE(trader_cdleveningdojistar, arg_info_trader_cdleveningdojistar)
	PHP_FE(trader_cdleveningstar, arg_info_trader_cdleveningstar)
	PHP_FE(trader_cdlgapsidesidewhite, arg_info_trader_cdlgapsidesidewhite)
	PHP_FE(trader_cdlgravestonedoji, arg_info_trader_cdlgravestonedoji)
	PHP_FE(trader_cdlhammer, arg_info_trader_cdlhammer)
	PHP_FE(trader_cdlhangingman, arg_info_trader_cdlhangingman)
	PHP_FE(trader_cdlharami, arg_info_trader_cdlharami)
	PHP_FE(trader_cdlharamicross, arg_info_trader_cdlharamicross)
	PHP_FE(trader_cdlhighwave, arg_info_trader_cdlhighwave)
	PHP_FE(trader_cdlhikkake, arg_info_trader_cdlhikkake)
	PHP_FE(trader_cdlhikkakemod, arg_info_trader_cdlhikkakemod)
	PHP_FE(trader_cdlhomingpigeon, arg_info_trader_cdlhomingpigeon)
	PHP_FE(trader_cdlidentical3crows, arg_info_trader_cdlidentical3crows)
	PHP_FE(trader_cdlinneck, arg_info_trader_cdlinneck)
	PHP_FE(trader_cdlinvertedhammer, arg_info_trader_cdlinvertedhammer)
	PHP_FE(trader_cdlkicking, arg_info_trader_cdlkicking)
	PHP_FE(trader_cdlkickingbylength, arg_info_trader_cdlkickingbylength)
	PHP_FE(trader_cdlladderbottom, arg_info_trader_cdlladderbottom)
	PHP_FE(trader_cdllongleggeddoji, arg_info_trader_cdllongleggeddoji)
	PHP_FE(trader_cdllongline, arg_info_trader_cdllongline)
	PHP_FE(trader_cdlmarubozu, arg_info_trader_cdlmarubozu)
	PHP_FE(trader_cdlmatchinglow, arg_info_trader_cdlmatchinglow)
	PHP_FE(trader_cdlmathold, arg_info_trader_cdlmathold)
	PHP_FE(trader_cdlmorningdojistar, arg_info_trader_cdlmorningdojistar)
	PHP_FE(trader_cdlmorningstar, arg_info_trader_cdlmorningstar)
	PHP_FE(trader_cdlonneck, arg_info_trader_cdlonneck)
	PHP_FE(trader_cdlpiercing, arg_info_trader_cdlpiercing)
	PHP_FE(trader_cdlrickshawman, arg_info_trader_cdlrickshawman)
	PHP_FE(trader_cdlrisefall3methods, arg_info_trader_cdlrisefall3methods)
	PHP_FE(trader_cdlseparatinglines, arg_info_trader_cdlseparatinglines)
	PHP_FE(trader_cdlshootingstar, arg_info_trader_cdlshootingstar)
	PHP_FE(trader_cdlshortline, arg_info_trader_cdlshortline)
	PHP_FE(trader_cdlspinningtop, arg_info_trader_cdlspinningtop)
	PHP_FE(trader_cdlstalledpattern, arg_info_trader_cdlstalledpattern)
	PHP_FE(trader_cdlsticksandwich, arg_info_trader_cdlsticksandwich)
	PHP_FE(trader_cdltakuri, arg_info_trader_cdltakuri)
	PHP_FE(trader_cdltasukigap, arg_info_trader_cdltasukigap)
	PHP_FE(trader_cdlthrusting, arg_info_trader_cdlthrusting)
	PHP_FE(trader_cdltristar, arg_info_trader_cdltristar)
	PHP_FE(trader_cdlunique3river, arg_info_trader_cdlunique3river)
	PHP_FE(trader_cdlupsidegap2crows, arg_info_trader_cdlupsidegap2crows)
	PHP_FE(trader_cdlxsidegap3methods, arg_info_trader_cdlxsidegap3methods)
	PHP_FE(trader_ceil, arg_info_trader_ceil)
	PHP_FE(trader_cmo, arg_info_trader_cmo)
	PHP_FE(trader_correl, arg_info_trader_correl)
	PHP_FE(trader_cos, arg_info_trader_cos)
	PHP_FE(trader_cosh, arg_info_trader_cosh)
	PHP_FE(trader_dema, arg_info_trader_dema)
	PHP_FE(trader_div, arg_info_trader_div)
	PHP_FE(trader_dx, arg_info_trader_dx)
	PHP_FE(trader_ema, arg_info_trader_ema)
	PHP_FE(trader_exp, arg_info_trader_exp)
	PHP_FE(trader_floor, arg_info_trader_floor)
	PHP_FE(trader_ht_dcperiod, arg_info_trader_ht_dcperiod)
	PHP_FE(trader_ht_dcphase, arg_info_trader_ht_dcphase)
	PHP_FE(trader_ht_phasor, arg_info_trader_ht_phasor)
	PHP_FE(trader_ht_sine, arg_info_trader_ht_sine)
	PHP_FE(trader_ht_trendline, arg_info_trader_ht_trendline)
	PHP_FE(trader_ht_trendmode, arg_info_trader_ht_trendmode)
	PHP_FE(trader_imi, arg_info_trader_imi)
	PHP_FE(trader_kama, arg_info_trader_kama)
	PHP_FE(trader_linearreg, arg_info_trader_linearreg)
	PHP_FE(trader_linearreg_angle, arg_info_trader_linearreg_angle)
	PHP_FE(trader_linearreg_intercept, arg_info_trader_linearreg_intercept)
	PHP_FE(trader_linearreg_slope, arg_info_trader_linearreg_slope)
	PHP_FE(trader_ln, arg_info_trader_ln)
	PHP_FE(trader_log10, arg_info_trader_log10)
	PHP_FE(trader_ma, arg_info_trader_ma)
	PHP_FE(trader_macd, arg_info_trader_macd)
	PHP_FE(trader_macdext, arg_info_trader_macdext)
	PHP_FE(trader_macdfix, arg_info_trader_macdfix)
	PHP_FE(trader_mama, arg_info_trader_mama)
	PHP_FE(trader_mavp, arg_info_trader_mavp)
	PHP_FE(trader_max, arg_info_trader_max)
	PHP_FE(trader_maxindex, arg_info_trader_maxindex)
	PHP_FE(trader_medprice, arg_info_trader_medprice)
	PHP_FE(trader_mfi, arg_info_trader_mfi)
	PHP_FE(trader_midpoint, arg_info_trader_midpoint)
	PHP_FE(trader_midprice, arg_info_trader_midprice)
	PHP_FE(trader_min, arg_info_trader_min)
	PHP_FE(trader_minindex, arg_info_trader_minindex)
	PHP_FE(trader_minmax, arg_info_trader_minmax)
	PHP_FE(trader_minmaxindex, arg_info_trader_minmaxindex)
	PHP_FE(trader_minus_di, arg_info_trader_minus_di)
	PHP_FE(trader_minus_dm, arg_info_trader_minus_dm)
	PHP_FE(trader_mom, arg_info_trader_mom)
	PHP_FE(trader_mult, arg_info_trader_mult)
	PHP_FE(trader_natr, arg_info_trader_natr)
	PHP_FE(trader_obv, arg_info_trader_obv)
	PHP_FE(trader_plus_di, arg_info_trader_plus_di)
	PHP_FE(trader_plus_dm, arg_info_trader_plus_dm)
	PHP_FE(trader_ppo, arg_info_trader_ppo)
	PHP_FE(trader_roc, arg_info_trader_roc)
	PHP_FE(trader_rocp, arg_info_trader_rocp)
	PHP_FE(trader_rocr, arg_info_trader_rocr)
	PHP_FE(trader_rocr100, arg_info_trader_rocr100)
	PHP_FE(trader_rsi, arg_info_trader_rsi)
	PHP_FE(trader_sar, arg_info_trader_sar)
	PHP_FE(trader_sarext, arg_info_trader_sarext)
	PHP_FE(trader_sin, arg_info_trader_sin)
	PHP_FE(trader_sinh, arg_info_trader_sinh)
	PHP_FE(trader_sma, arg_info_trader_sma)
	PHP_FE(trader_sqrt, arg_info_trader_sqrt)
	PHP_FE(trader_stddev, arg_info_trader_stddev)
	PHP_FE(trader_stoch, arg_info_trader_stoch)
	PHP_FE(trader_stochf, arg_info_trader_stochf)
	PHP_FE(trader_stochrsi, arg_info_trader_stochrsi)
	PHP_FE(trader_sub, arg_info_trader_sub)
	PHP_FE(trader_sum, arg_info_trader_sum)
	PHP_FE(trader_t3, arg_info_trader_t3)
	PHP_FE(trader_tan, arg_info_trader_tan)
	PHP_FE(trader_tanh, arg_info_trader_tanh)
	PHP_FE(trader_tema, arg_info_trader_tema)
	PHP_FE(trader_trange, arg_info_trader_trange)
	PHP_FE(trader_trima, arg_info_trader_trima)
	PHP_FE(trader_trix, arg_info_trader_trix)
	PHP_FE(trader_tsf, arg_info_trader_tsf)
	PHP_FE(trader_typprice, arg_info_trader_typprice)
	PHP_FE(trader_ultosc, arg_info_trader_ultosc)
	PHP_FE(trader_var, arg_info_trader_var)
	PHP_FE(trader_wclprice, arg_info_trader_wclprice)
	PHP_FE(trader_willr, arg_info_trader_willr)
	PHP_FE(trader_wma, arg_info_trader_wma)
	PHP_FE_END
};

#endif /* TA_PHP_FE_H */

