name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
    steps:
    - uses: actions/checkout@v1
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - name: Update PECL
      run: pecl channel-update pecl.php.net
    - name: Install ext-trader
      run: pecl install trader
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run tests
      run: php vendor/bin/phpunit
