name: PHPUnit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1, 8.2]
    steps:
    - uses: actions/checkout@v1
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: pecl
        extensions: trader
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run tests
      run: php vendor/bin/phpunit
